/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ReceiverRouteImport } from './routes/$receiver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamMetaRouteImport } from './routes/api/stream-meta'
import { Route as ApiIcecastRouteImport } from './routes/api/icecast'
import { Route as ApiStreamSplatRouteImport } from './routes/api/stream.$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverRoute = ReceiverRouteImport.update({
  id: '/$receiver',
  path: '/$receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamMetaRoute = ApiStreamMetaRouteImport.update({
  id: '/api/stream-meta',
  path: '/api/stream-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIcecastRoute = ApiIcecastRouteImport.update({
  id: '/api/icecast',
  path: '/api/icecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamSplatRoute = ApiStreamSplatRouteImport.update({
  id: '/api/stream/$',
  path: '/api/stream/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$receiver': typeof ReceiverRoute
  '/admin': typeof AdminRoute
  '/api/icecast': typeof ApiIcecastRoute
  '/api/stream-meta': typeof ApiStreamMetaRoute
  '/api/stream/$': typeof ApiStreamSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$receiver': typeof ReceiverRoute
  '/admin': typeof AdminRoute
  '/api/icecast': typeof ApiIcecastRoute
  '/api/stream-meta': typeof ApiStreamMetaRoute
  '/api/stream/$': typeof ApiStreamSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$receiver': typeof ReceiverRoute
  '/admin': typeof AdminRoute
  '/api/icecast': typeof ApiIcecastRoute
  '/api/stream-meta': typeof ApiStreamMetaRoute
  '/api/stream/$': typeof ApiStreamSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$receiver'
    | '/admin'
    | '/api/icecast'
    | '/api/stream-meta'
    | '/api/stream/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$receiver'
    | '/admin'
    | '/api/icecast'
    | '/api/stream-meta'
    | '/api/stream/$'
  id:
    | '__root__'
    | '/'
    | '/$receiver'
    | '/admin'
    | '/api/icecast'
    | '/api/stream-meta'
    | '/api/stream/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiverRoute: typeof ReceiverRoute
  AdminRoute: typeof AdminRoute
  ApiIcecastRoute: typeof ApiIcecastRoute
  ApiStreamMetaRoute: typeof ApiStreamMetaRoute
  ApiStreamSplatRoute: typeof ApiStreamSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$receiver': {
      id: '/$receiver'
      path: '/$receiver'
      fullPath: '/$receiver'
      preLoaderRoute: typeof ReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-meta': {
      id: '/api/stream-meta'
      path: '/api/stream-meta'
      fullPath: '/api/stream-meta'
      preLoaderRoute: typeof ApiStreamMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icecast': {
      id: '/api/icecast'
      path: '/api/icecast'
      fullPath: '/api/icecast'
      preLoaderRoute: typeof ApiIcecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$': {
      id: '/api/stream/$'
      path: '/api/stream/$'
      fullPath: '/api/stream/$'
      preLoaderRoute: typeof ApiStreamSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiverRoute: ReceiverRoute,
  AdminRoute: AdminRoute,
  ApiIcecastRoute: ApiIcecastRoute,
  ApiStreamMetaRoute: ApiStreamMetaRoute,
  ApiStreamSplatRoute: ApiStreamSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
